Repository Space2Study-UA-1156/BackEnd-02, pull requests merged in 2024-05, with the labels that each got.

#56 Added populated 'author' fields in comments for POST and GET methods #44
  src/models/comment.js
  src/services/comment.js
Labels: bug, Backend, sprint 1

#58 Fixed issue with third-party comments for a cooperation #43
  src/services/comment.js
Labels: bug, Backend, sprint 1

#61 removed logic for sendEmail confirmation
  src/services/auth.js
Labels: bug, Backend, feature

#63 Updated "Category" constants #62
  src/consts/categories.js
  src/models/category.js
Labels: Backend, Categories, sprint 3

#68 Extended JWT Token with firstName, lastName, and email claims #67
  src/services/auth.js
Labels: Backend, feature, sprint 4

#70 Added population of MongoDB documents for "Subjects" upon database initialization #69
  docs/category/category-schema.yaml
  docs/category/category.yaml
  src/consts/subjects.js
  src/initialization/serverSetup.js
  src/seed/checkSubjectExistence.js
  src/seed/seedSubject.js
Labels: bug, Backend, Categories, feature, sprint 4

#73 Extended the user data by incorporating the "isRegistrationCompleted" field #72
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/models/user.js
  src/services/auth.js
  src/services/user.js
  src/test/integration/controllers/user.spec.js
  src/utils/users/createAggregateOptions.js
Labels: Backend, feature, sprint 5

#77 Extended the user data by incorporating the "spokenLanguages" field #76
  docs/review/review.yaml
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/consts/validation.js
  src/models/user.js
  src/validation/services/user.js
Labels: Backend, feature, sprint 5

#75 Fixed bug when updating user's native language #74
  src/consts/validation.js
  src/models/user.js
Labels: bug, Backend, sprint 5

#71 (SP: 1) Subject model validation #66
  src/models/subject.js
Labels: Backend, sprint 5

#79 Created "Avatar" service #78
  .gitignore
  src/consts/errors.js
  src/initialization/initialization.js
  src/services/avatar.js
  src/services/user.js
Labels: Backend, feature, sprint 5

#80 Added involvement check before updating/deleting Offers #64
  docs/offer/offer.yaml
  src/controllers/offer.js
  src/services/offer.js
  src/test/integration/controllers/offer.spec.js
Labels: Backend, feature, Find offers, sprint 5

#81 Added "Offer" model validation #65
  src/models/offer.js
Labels: Backend, feature, Find offers, sprint 5

#60 (SP: 1) Category model validation #59
  src/models/category.js
Labels: Backend, Categories, feature

#85 Extended JWT token with "photo" claim #84
  src/services/auth.js
Labels: Backend, feature, sprint 6

#83 Created "User Requests" endpoint #82
  docs/userRequest/user-request-schema.yaml
  docs/userRequest/user-request.yaml
  src/consts/models.js
  src/controllers/userRequest.js
  src/models/userRequest.js
  src/routes/index.js
  src/routes/userRequest.js
  src/services/userRequest.js
  src/validation/services/userRequest.js
Labels: Backend, Categories, feature, Subjects, sprint 6
