Repository Space2Study-UA-1156/BackEnd-02, pull requests merged in 2024-04, with the labels that each got.

#49 Updated configuration files for SonarCloud
  .github/workflows/main.yaml
  sonar-project.properties
Labels: sprint 1

#53 Fixed issue with total offer calculation for specific categories and roles #39
  src/models/offer.js
Labels: bug, Backend, sprint 1

#57 Added authorAvgRating calculation #42
  src/models/review.js
Labels: bug, Backend, sprint 1

#52 Fixed issue with total offer calculation for specific subjects and roles #38
  src/models/offer.js
Labels: bug, Backend, sprint 1

#55 Added validation for changing price and cooperation status simultaneously #45
  src/services/cooperation.js
Labels: bug, Backend, sprint 1

#54 Fixed issue with recalculating totalOffers value after deleting an offer #40
  src/models/offer.js
Labels: bug, Backend, sprint 1

#51 36: Any user can update/delete reviews
  src/controllers/review.js
  src/services/review.js
Labels: bug, Backend
